apiVersion: v1
kind: Service
metadata:
  labels:
    name: service-simple
  name: service-simple
spec:
  type: LoadBalancer
  ports:
    # The port that this service should serve on.
    - port: 8088
      targetPort: 3000
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    name: node-simple
